### PR TITLE
ci: update workflows to latest version

### PR DESCRIPTION
**Pull request by kayman-mk**
# Description

Updates the workflows to point to the latest version.

# Verification

Done via workflows in this feature branch.

### CODE REVIEW

**Comment by kayman-mk** [comment]
requires #313

**Review by PascalFrenz — APPROVED** [review]

**Comment by PascalFrenz** [comment]
@kayman-mk I updated the MR by rebasing against master after merging #313. I think you have to review & merge now :)

**Comment by kayman-mk** [comment]
@PascalFrenz I am not allowed to approve. @NewCeptionDev Can you help?

**Review by NewCeptionDev — APPROVED** [review]

**Pull request merged**
