### PR TITLE
feat: allow mixture of on-demand and spot instances

### PR DESCRIPTION
**Pull request by MauroSoli**
# Description

Added the possibility of choosing the preferred balance to mix on-demand and Spot instances on the `on_spot`  aws_autoscaling_group resource. As spot instances might be stopped without further notice, it might be useful to deploy at least one on-demand instance.

Use the new variable `instances_distribution` to customize the minimum number of on_demand instances and the percentage of on_demand instances (excluding the on_demand base capacity). 

```hcl
module "bastion" {
  ...
  instances_distribution = {
    on_demand_base_capacity                  = 1
    on_demand_percentage_above_base_capacity = 20
    spot_allocation_strategy                 = "lowest-price"
  }
}
```

# Verification

- [x] simple example applied, still running
- [x] mixture of 3:1 (spot:on-demand) instances (4 in total). Both instances are created and I am able to connect.

# Checklist

- [x] My code follows the style guidelines of the project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kayman-mk** [comment]
Thanks for your work! I have to dig in a little further.

praise: Very detailed example. Could you please add it to the `examples/` directory? As the PR title description is used for the commit I would remove it here (simply too long). But it is worth to remain.

**Comment by kayman-mk** [comment]
Could you please add some sentences to describe the problem solved? If it is availabilitiness, we should add a tag or similar to the EC2 instances to be able to identify them when connecting. Otherwise you can't be sure to get the non spot instance.

**Comment by kayman-mk** [comment]
Seems that it is not possible to have different tags for on-demand/spot instances. So let's drop that requirement for now.

**Comment by kayman-mk** [comment]
Almost ready to merge

- @MauroSoli waiting for some details in the PR description (see [comment](https://github.com/Hapag-Lloyd/terraform-aws-bastion-host-ssm/pull/140#issuecomment-1404649244))
- example from PR removed. Stored a copy on my local machine if needed.

**Review by kayman-mk — APPROVED** [review]

**Comment by MauroSoli** [comment]
Yeah, unfortunately, it's not possible to have different tags for mixed instances.
That is not a problem in my case because I simply use a bash function to connect on aws_bastion:

```bash
function bastion_aws_ondemand() {
aws ec2 describe-instances \
    --filters "Name=tag:Name,Values='bastion'" \
              "Name=instance-state-name,Values=running" \
    --query "Reservations[*].Instances[*].{Instance:InstanceId,lifecycle:InstanceLifecycle}" \
    --output text | grep None | awk '{print $1}' | shuf -n 1}
```

Anyway, could be worthwhile in future to manage user data on the launch template to change prefix hostname based on instance type (spot, on_demand).  Something like that: https://docs.amazonaws.cn/en_us/autoscaling/ec2/userguide/tutorial-lifecycle-hook-instance-metadata.html

**Review by kayman-mk — APPROVED** [review]
Ready to merge, but waiting for PR amendment.

**Comment by kayman-mk** [comment]
Yeap. Just looking for some details, why this feature is useful. See here: https://github.com/Hapag-Lloyd/terraform-aws-bastion-host-ssm/pull/140#issuecomment-1404649244

**Comment by kayman-mk** [comment]
Sorry, wrong link;: https://github.com/Hapag-Lloyd/terraform-aws-bastion-host-ssm/pull/140#issuecomment-1404643451

**Comment by MauroSoli** [comment]
PR description updated

**Pull request merged**
